apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s  # Frecuencia para recolectar métricas

    scrape_configs:
      - job_name: 'spring-boot'
        static_configs:
          - targets: ['spring-boot:8080']  # Nombre del servicio y puerto
